[project]
name = "py-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["projects/server"]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
