[project]
name = "server"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi>=0.115.13",
    "uvicorn>=0.34.3",
]

[dependency-groups]
dev = [
    "uvicorn>=0.34.3",
]
