name: Automated code QA
on:
- push
jobs:
  Run-ruff-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run ruff
      run: |
        uv run ruff check